### ISSUE TITLE
Cannot run JSR330 TCK tests

### ISSUE THREAD

**Issue by cgruber** [javax-inject/javax-inject#23]
_From [fast....@gmail.com](https://code.google.com/u/109684022697187098226/) on July 18, 2011 22:33:49_

Hi
I apologize if this is the wrong place to post this issue - if someone could direct me to where I can raise this issue in that case, I'd appreciate it.

I am trying to run the JSR330 TCK tests on Windows 2003.
According to the Readme accompanying the JSR330 TCK porting, I have installed the 330 TCK, the 330 tck glassfish porting package (Dec 7, 2009 version), the 299 TCK (version 1.0.4SP1).
I update the build.properties file according to above installations and then I invoke the ant run command to run the tests.

The following is the output from the run:

C:\jsr330\330-tck-glassfish-porting>ant run
Buildfile: build.xml

run:
    [junit] Testsuite: org.jboss.weld.atinject.tck.AtInjectTCK
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0 sec
    [junit] ------------- Standard Error -----------------
    [junit] Jul 19, 2011 5:21:44 AM org.jboss.weld.bootstrap.WeldBootstrap \<clinit>
    [junit] INFO: WELD-000900 1.1.0 (is)
    [junit] ------------- ---------------- ---------------
    [junit]
    [junit]     Caused an ERROR
    [junit] null
    [junit] java.lang.reflect.InvocationTargetException
    [junit] Caused by: java.lang.NoSuchMethodError: org.jboss.weld.bootstrap.WeldBootstrap.startContainer(Lorg/jboss/wel
d/bootstrap/api/Environment;Lorg/jboss/weld/bootstrap/spi/Deployment;Lorg/jboss/weld/context/api/BeanStore;)Lorg/jboss/w
eld/bootstrap/api/Bootstrap;
    [junit]     at org.jboss.weld.mock.MockServletLifecycle.initialize(MockServletLifecycle.java:92)
    [junit]     at org.jboss.weld.mock.TestContainer.startContainer(TestContainer.java:84)
    [junit]     at org.jboss.weld.atinject.tck.AtInjectTCK.suite(AtInjectTCK.java:65)
    [junit]
    [junit] Test org.jboss.weld.atinject.tck.AtInjectTCK FAILED

report:
[junitreport] the file C:\tmp\output\TESTS-TestSuites.xml is not a valid testsuite XML document
[junitreport] Processing C:\tmp\output\TESTS-TestSuites.xml to D:\Users\INTERS~1\AppData\Local\Temp\2\null905322556
[junitreport] Loading stylesheet jar:file:/C:/javaeetck/tools/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optio
nal/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 938ms
[junitreport] Deleting: D:\Users\INTERS~1\AppData\Local\Temp\2\null905322556
     [echo] Report written to /tmp/output

BUILD SUCCESSFUL
Total time: 5 seconds

Can someone help me run this JSR330 TCK successfully? Thanks!

Regards
Noman

_Original issue: http://code.google.com/p/atinject/issues/detail?id=24_

**Comment by cgruber** [comment]
_From [fast....@gmail.com](https://code.google.com/u/109684022697187098226/) on July 18, 2011 23:19:56_

Instead of using the JSR299 TCK, I first used the JSR299 TCK porting package and pointed to that as the 299.tck.home. This produced a ClassNotFoundException.

The latest JSR330 related files that I used are:

1.	330-tck-glassfish-porting-1.0_07-Dec-2009.zip (the JSR330 porting package)
2.	javax.inject-tck.zip the JSR330 TCK)
3.	299-tck-glassfish-porting-1.0_17-Jun-2011.zip (the JSR299 porting package)

Here is the output from that run:

C:\jsr330\330-tck-glassfish-porting>ant run
Buildfile: build.xml

run:
    [junit] Testsuite: org.jboss.weld.atinject.tck.AtInjectTCK
    [junit] Tests run: 1, Failures: 0, Errors: 1, Time elapsed: 0 sec
    [junit]
    [junit]     Caused an ERROR
    [junit] org/jboss/weld/mock/MockServletLifecycle
    [junit] java.lang.NoClassDefFoundError: org/jboss/weld/mock/MockServletLifecycle
    [junit]     at java.lang.Class.forName0(Native Method)
    [junit]     at java.lang.Class.forName(Class.java:247)
    [junit] Caused by: java.lang.ClassNotFoundException: org.jboss.weld.mock.MockServletLifecycle
    [junit]     at java.lang.ClassLoader.loadClass(ClassLoader.java:248)
    [junit]
    [junit] Test org.jboss.weld.atinject.tck.AtInjectTCK FAILED

report:
[junitreport] the file C:\tmp\output\TESTS-TestSuites.xml is not a valid testsuite XML document
[junitreport] Processing C:\tmp\output\TESTS-TestSuites.xml to D:\Users\INTERS~1\AppData\Local\Temp\2\null275437358
[junitreport] Loading stylesheet jar:file:/C:/javaeetck/tools/ant/lib/ant-junit.jar!/org/apache/tools/ant/taskdefs/optio
nal/junit/xsl/junit-frames.xsl
[junitreport] Transform time: 968ms
[junitreport] Deleting: D:\Users\INTERS~1\AppData\Local\Temp\2\null275437358
     [echo] Report written to /tmp/output

BUILD SUCCESSFUL
Total time: 5 seconds

**Comment by cgruber** [comment]
_From [pm...@bleepbleep.org.uk](https://code.google.com/u/111430394170208252812/) on July 19, 2011 05:32:39_

I think you would be better off reporting/discussing this on the GlassFish forums, the setup of the CDI and AtInject TCKs you are showing is very GlassFish specific.

**Comment by cgruber** [comment]
_From [fast....@gmail.com](https://code.google.com/u/109684022697187098226/) on July 19, 2011 18:14:11_

Thanks. I'll try the Glassfish forums. I was hoping the creators/maintainers of the JSR330 tck could help.
